In [0]:
#Reading single File
df_s = spark.read.format("csv").option("inferSchema", True).option("header", True).option("sep",",").load("/FileStore/tables/employee.csv")

display (df_s)
# gives number of records/row counts
print(df_s.count())

df_s.printSchema()

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Mohan,S.,9,60000
20,Harish,K,2,25000
30,Ashish,XYZ,3,30000
40,Anupam,BBB,5,40000
50,Xaviour,XYZ,8,50000
60,john,null,2,null
null,**,**,null,8000
null,null,null,null,null
90,kamal,xyz,7,70000

9
root
 |-- Employee_id: integer (nullable = true)
 |-- Emp_First_name: string (nullable = true)
 |-- Emp_Last_Same: string (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [0]:
#Reading single File
df_s1 = spark.read.format("csv").options(inferSchema= True, header= True, sep= ",").load("/FileStore/tables/employee.csv")

display (df_s1)
# gives number of records/row counts
print(df_s1.count())

df_s1.printSchema()

Employee_id,Emp_First_name,Emp_Last_Same,Experience,Salary
10,Mohan,S.,9,60000
20,Harish,K,2,25000
30,Ashish,XYZ,3,30000
40,Anupam,BBB,5,40000
50,Xaviour,XYZ,8,50000
60,john,null,2,null
null,**,**,null,8000
null,null,null,null,null
90,kamal,xyz,7,70000

9
root
 |-- Employee_id: integer (nullable = true)
 |-- Emp_First_name: string (nullable = true)
 |-- Emp_Last_Same: string (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [0]:
"""
Creating dataframe by using CustomSchema
"""
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType, DateType

"""
StructField("name of column", datatypeo of column(), Nullable Flag(True), metadata),
"""
retailSchema = StructType([StructField("InvoiceNo", IntegerType(), True), \
                         StructField("StockCode", StringType(), True), \
                         StructField("Description", StringType(), True), \
                         StructField("Quantity", IntegerType(), True), \
                         #StructField("InvoiceDate", DateType(), True),\
                         StructField("InvoiceDate", TimestampType(), True),\
                         StructField("UnitPrice", DoubleType(), True),\
                         StructField("CustomerID", IntegerType(), True),\
                         StructField("Country", StringType(), True), \
                         StructField("dummy_date", DateType(), True)
                        ])
print(retailSchema)

StructType(List(StructField(InvoiceNo,IntegerType,true),StructField(StockCode,StringType,true),StructField(Description,StringType,true),StructField(Quantity,IntegerType,true),StructField(InvoiceDate,TimestampType,true),StructField(UnitPrice,DoubleType,true),StructField(CustomerID,IntegerType,true),StructField(Country,StringType,true),StructField(dummy_date,DateType,true)))

In [0]:
retailDF1= spark.read.format('csv').options(header='True', sep= ',', quote='"', mode='PERMISSIVE') \
                     .schema(retailSchema) \
                     .load('/FileStore/tables/Online_Retail-1.csv')

print("dataframe: retailDF1")
retailDF1.show(truncate=False)
retailDF1.printSchema()
print('Shape of retailDF1:', retailDF1.count(), ' * ', len(retailDF1.columns))

dataframe: retailDF1
+---------+---------+-----------------------------------+--------+-------------------+---------+----------+--------------+----------+
|InvoiceNo|StockCode|Description                        |Quantity|InvoiceDate        |UnitPrice|CustomerID|Country       |dummy_date|
+---------+---------+-----------------------------------+--------+-------------------+---------+----------+--------------+----------+
|536365   |85123A   |WHITE HANGING HEART T-LIGHT HOLDER |6       |2010-12-01 08:26:00|2.55     |17850     |United Kingdom|2022-01-01|
|536365   |71053    |WHITE METAL LANTERN                |6       |2010-12-01 08:26:00|3.39     |17850     |United Kingdom|2022-11-02|
|536365   |84406B   |CREAM CUPID HEARTS COAT HANGER     |8       |2010-12-01 08:26:00|2.75     |17850     |United Kingdom|2022-07-31|
|536365   |84029G   |KNITTED UNION FLAG HOT WATER BOTTLE|6       |2010-12-01 08:26:00|3.39     |17850     |United Kingdom|2022-01-04|
|536365   |84029E   |RED WOOLLY HOTTIE WHITE HEART.     |6       |2010-12-01 08:26:00|3.39     |17850     |United Kingdom|2022-01-05|
|536365   |22752    |SET 7 BABUSHKA NESTING BOXES       |2       |2010-12-01 08:26:00|7.65     |17850     |United Kingdom|2022-01-06|
|536365   |21730    |GLASS STAR FROSTED T-LIGHT HOLDER  |6       |2010-12-01 08:26:00|4.25     |17850     |United Kingdom|2022-01-07|
|536366   |22633    |HAND WARMER UNION JACK             |6       |2010-12-01 08:28:00|1.85     |17850     |United Kingdom|2022-01-08|
|536366   |22632    |HAND WARMER RED POLKA DOT          |6       |2010-12-01 08:28:00|1.85     |17850     |United Kingdom|2022-01-09|
|536367   |84879    |ASSORTED COLOUR BIRD ORNAMENT      |32      |2010-12-01 08:34:00|1.69     |13047     |United Kingdom|2022-01-10|
|536367   |22745    |POPPY'S PLAYHOUSE BEDROOM          |6       |2010-12-01 08:34:00|2.1      |13047     |United Kingdom|2022-01-11|
|536367   |22748    |POPPY'S PLAYHOUSE KITCHEN          |6       |2010-12-01 08:34:00|2.1      |13047     |United Kingdom|2022-01-12|
|536367   |22749    |FELTCRAFT PRINCESS CHARLOTTE DOLL  |8       |2010-12-01 08:34:00|3.75     |13047     |United Kingdom|2022-01-13|
|536367   |22310    |IVORY KNITTED MUG COSY             |6       |2010-12-01 08:34:00|1.65     |13047     |United Kingdom|2022-01-14|
|536367   |84969    |BOX OF 6 ASSORTED COLOUR TEASPOONS |6       |2010-12-01 08:34:00|4.25     |13047     |United Kingdom|2022-01-15|
|536367   |22623    |BOX OF VINTAGE JIGSAW BLOCKS       |3       |2010-12-01 08:34:00|4.95     |13047     |United Kingdom|2022-01-16|
|536367   |22622    |BOX OF VINTAGE ALPHABET BLOCKS     |2       |2010-12-01 08:34:00|9.95     |13047     |United Kingdom|2022-01-17|
|536367   |21754    |HOME BUILDING BLOCK WORD           |3       |2010-12-01 08:34:00|5.95     |13047     |United Kingdom|2022-01-18|
|536367   |21755    |LOVE BUILDING BLOCK WORD           |3       |2010-12-01 08:34:00|5.95     |13047     |United Kingdom|2022-01-19|
|536367   |21777    |RECIPE BOX WITH METAL HEART        |4       |2010-12-01 08:34:00|7.95     |13047     |United Kingdom|2022-01-20|
+---------+---------+-----------------------------------+--------+-------------------+---------+----------+--------------+----------+
only showing top 20 rows

root
 |-- InvoiceNo: integer (nullable = true)
 |-- StockCode: string (nullable = true)
 |-- Description: string (nullable = true)
 |-- Quantity: integer (nullable = true)
 |-- InvoiceDate: timestamp (nullable = true)
 |-- UnitPrice: double (nullable = true)
 |-- CustomerID: integer (nullable = true)
 |-- Country: string (nullable = true)
 |-- dummy_date: date (nullable = true)

Shape of retailDF1: 70  *  9